// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkJ-Otq2KaGiZc21M8rxnDuOgEfEsAQ6A',
    appId: '1:468189408152:web:18437202209b215a8fd9ed',
    messagingSenderId: '468189408152',
    projectId: 'printfastfirebase',
    authDomain: 'printfastfirebase.firebaseapp.com',
    databaseURL: 'https://printfastfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'printfastfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmcOKxl9R_2OMT6SYS3aWs4jymC2_etQ',
    appId: '1:468189408152:android:78bdef2064eec3528fd9ed',
    messagingSenderId: '468189408152',
    projectId: 'printfastfirebase',
    databaseURL: 'https://printfastfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'printfastfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdIkhjeOX9tEfb-lj_lifMzXVXFXJtpDY',
    appId: '1:468189408152:ios:c87f6546791341f78fd9ed',
    messagingSenderId: '468189408152',
    projectId: 'printfastfirebase',
    databaseURL: 'https://printfastfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'printfastfirebase.appspot.com',
    iosBundleId: 'com.example.printFast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdIkhjeOX9tEfb-lj_lifMzXVXFXJtpDY',
    appId: '1:468189408152:ios:ce85a46b5bffc0d58fd9ed',
    messagingSenderId: '468189408152',
    projectId: 'printfastfirebase',
    databaseURL: 'https://printfastfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'printfastfirebase.appspot.com',
    iosBundleId: 'com.example.printFast.RunnerTests',
  );
}
