// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRlpPh55inZGXZr7W1KEHDJLHwbGJv50',
    appId: '1:213366385233:web:45c7047d302040014c2670',
    messagingSenderId: '213366385233',
    projectId: 'printfastoficial',
    authDomain: 'printfastoficial.firebaseapp.com',
    storageBucket: 'printfastoficial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdIeP885DykIgdfjPk3Peo4x3Dip7_Xt0',
    appId: '1:213366385233:android:7ef4144de40b3d074c2670',
    messagingSenderId: '213366385233',
    projectId: 'printfastoficial',
    storageBucket: 'printfastoficial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmCkXoSCFPkUVT-Wp7kpyaUlFauWUX5A4',
    appId: '1:213366385233:ios:0abac7d13e65c8de4c2670',
    messagingSenderId: '213366385233',
    projectId: 'printfastoficial',
    storageBucket: 'printfastoficial.appspot.com',
    iosBundleId: 'com.example.printFast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmCkXoSCFPkUVT-Wp7kpyaUlFauWUX5A4',
    appId: '1:213366385233:ios:ba941fa1d66f58cd4c2670',
    messagingSenderId: '213366385233',
    projectId: 'printfastoficial',
    storageBucket: 'printfastoficial.appspot.com',
    iosBundleId: 'com.example.printFast.RunnerTests',
  );
}
